import fs from "node:fs";
import path from "node:path";

const root=path.resolve(".");
const appDir=path.join(root,"app");
const appHtml=fs.readdirSync(appDir).filter(x=>x.endsWith(".html"));
if(appHtml.length!==1||appHtml[0]!=="index.html")throw new Error("Page source duplication detected: "+appHtml.join(", "));

const index=fs.readFileSync(path.join(appDir,"index.html"),"utf8");
const app=fs.readFileSync(path.join(appDir,"app.js"),"utf8");
const workflow=fs.readFileSync(path.join(root,".github/workflows/deploy-pages.yml"),"utf8");
const builder=fs.readFileSync(path.join(root,"scripts/build-pages.mjs"),"utf8");
const readme=fs.readFileSync(path.join(root,"README.md"),"utf8");
const supabaseConfig=fs.readFileSync(path.join(root,"supabase/config.toml"),"utf8");
if(!fs.existsSync(path.join(root,"supabase/functions/admin-user/index.ts")))throw new Error("admin-user source missing");
if(!fs.existsSync(path.join(root,"supabase/functions/bootstrap-admin/index.ts")))throw new Error("bootstrap-admin source missing");
if(!supabaseConfig.includes('project_id = "xdfwtsixuwikijknkvlz"'))throw new Error("Supabase project config missing");

if(!index.includes('<base href="/FIBER-ANALIZER/">'))throw new Error("GitHub Pages base path missing");
if(!index.includes('src="./app.js?v='))throw new Error("app.js cache-busting version missing");
if(!index.includes('data-page="dashboard"'))throw new Error("Canonical dashboard page marker missing");
if(!app.includes('const APP_BASE="/FIBER-ANALIZER"'))throw new Error("Application base path missing");
if(app.includes("localStorage"))throw new Error("Network data must not use localStorage as a persistence source");
if(app.includes("from(\"network_state\").upsert"))throw new Error("Legacy network_state snapshot must not be written");
if(!app.includes("async function syncNetworkData"))throw new Error("Normalized network persistence service missing");
if(!app.includes("async function syncOltFoundation"))throw new Error("Normalized OLT foundation persistence service missing");
if(!app.includes('"olt_ports"'))throw new Error("OLT port foundation table is not wired");
if(!app.includes("syncOltFoundation()"))throw new Error("OLT foundation sync is not part of persistence flow");
if(!app.includes('"network_nodes"')||!app.includes('"cables"')||!app.includes('"cable_cores"')||!app.includes('"splices"')||!app.includes('"service_paths"'))throw new Error("Fiber foundation reconciliation is incomplete");
if(!app.includes("function navigateContext")||!app.includes("function applyPageContext"))throw new Error("Contextual cross-page navigation missing");
if(!app.includes('data-customer-context'))throw new Error("Customer contextual actions missing");
for(const form of ["assetForm","cableForm","connectionForm","splitterForm","splitterConnectionForm"])if(!app.includes(`$("`+form+`").onsubmit`))throw new Error(`Persistence handler missing: ${form}`);
if(!app.includes("from(\"customers\")"))throw new Error("Normalized customer table is not wired");
if(!workflow.includes("branches:\n      - main"))throw new Error("Pages deployment must be main-only");
if(workflow.includes("feature/fiber-network-foundation"))throw new Error("Feature branch must not deploy to production Pages");
if(!workflow.includes("node scripts/build-pages.mjs"))throw new Error("Page build step missing");
if(!builder.includes("dashboard.html")||!builder.includes("settings.html"))throw new Error("Page manifest incomplete");
if(!readme.includes("OLT → OLT Port → OTB → JB → BOX ODC-ODP → BOX ODC → BOX ODP → Customer"))throw new Error("README topology is stale");
if(readme.includes("OLT → PON → JB → ODC → ODP → Customer"))throw new Error("Legacy README topology leaked");
console.log("project structure integrity test passed");