import {shortestTrace,coreTrace,validateGraph} from "./graph-engine.js";
const KEY="fiber-analyzer-flex-v1";
const topology=["OLT","PON","JB","ODC","ODP","CUSTOMER"];
const seed={assets:[
{id:"olt-1",type:"OLT",code:"OLT-01",name:"OLT Utama",status:"ACTIVE"},
{id:"jb-1",type:"JB",code:"JB-01",name:"Joint Box 01",status:"ACTIVE"},
{id:"jb-2",type:"JB",code:"JB-02",name:"Joint Box 02",status:"ACTIVE"},
{id:"jb-3",type:"JB",code:"JB-03",name:"Joint Box 03",status:"ACTIVE"},
{id:"odc-1",type:"ODC",code:"ODC-01",name:"ODC Utama",status:"ACTIVE"},
{id:"odp-1",type:"ODP",code:"ODP-01",name:"ODP 01",status:"ACTIVE"},
{id:"c-1",type:"CUSTOMER",code:"CUST-001",name:"Pelanggan Demo",status:"ACTIVE"}],
links:[{id:"svc-1",from:"odp-1",to:"c-1",kind:"SERVICE"}],splices:[],
cables:[
{id:"cab-olt-jb1",code:"KBL-OLT-JB01-24C",fiber_count:24,length_m:1000,from:"olt-1",to:"jb-1",status:"ACTIVE"},
{id:"cab-jb1-jb2",code:"KBL-JB01-JB02-24C",fiber_count:24,length_m:600,from:"jb-1",to:"jb-2",status:"ACTIVE"},
{id:"cab-jb1-jb3",code:"KBL-JB01-JB03-12C",fiber_count:12,length_m:450,from:"jb-1",to:"jb-3",status:"ACTIVE"},
{id:"cab-jb2-odc",code:"KBL-JB02-ODC01-24C",fiber_count:24,length_m:700,from:"jb-2",to:"odc-1",status:"ACTIVE"},
{id:"cab-odc-odp",code:"KBL-ODC01-ODP01-12C",fiber_count:12,length_m:300,from:"odc-1",to:"odp-1",status:"ACTIVE"}],
cores:[
{id:"core-1",cable_id:"cab-olt-jb1",core_number:1,status:"IN_USE"},
{id:"core-2",cable_id:"cab-jb1-jb2",core_number:1,status:"IN_USE"},
{id:"core-3",cable_id:"cab-jb1-jb3",core_number:1,status:"IN_USE"},
{id:"core-4",cable_id:"cab-jb2-odc",core_number:1,status:"IN_USE"},
{id:"core-5",cable_id:"cab-odc-odp",core_number:1,status:"IN_USE"}],coreConnections:[{id:"cc-1",nodeId:"jb-1",inputCableId:"cab-olt-jb1",inputCoreId:"core-1",outputCableId:"cab-jb1-jb2",outputCoreId:"core-2",connectionType:"SPLICE",status:"ACTIVE"},{id:"cc-2",nodeId:"jb-2",inputCableId:"cab-jb1-jb2",inputCoreId:"core-2",outputCableId:"cab-jb2-odc",outputCoreId:"core-4",connectionType:"SPLICE",status:"ACTIVE"},{id:"cc-3",nodeId:"odc-1",inputCableId:"cab-jb2-odc",inputCoreId:"core-4",outputCableId:"cab-odc-odp",outputCoreId:"core-5",connectionType:"SPLICE",status:"ACTIVE"}]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||seed;db.coreConnections=db.coreConnections||[];
const $=id=>document.getElementById(id), save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function options(list,value,empty="— Tidak ada —"){return '<option value="">'+empty+'</option>'+list.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===value?"selected":"")+'>'+esc(x.code||x.name||x.id)+'</option>').join("")}
function fillCableInputs(a={}){const cables=db.cables||[],incoming=$( "assetIncomingCable"),outgoing=$( "assetOutgoingCable");if(!incoming)return;incoming.innerHTML=options(cables,a.incomingCableId);outgoing.innerHTML=options(cables,a.outgoingCableId);fillCore("assetIncomingCore",a.incomingCoreId,a.incomingCableId);fillCore("assetOutgoingCore",a.outgoingCoreId,a.outgoingCableId)}
function fillCore(id,value,cableId){const el=$(id);if(!el)return;const cores=(db.cores||[]).filter(c=>!cableId||c.cable_id===cableId);el.innerHTML=options(cores,value,"— Tidak ada core —");}
function render(){renderStats();renderAssets();renderCustomers();renderCores();renderCables();renderConnections()}
function nodeOptions(value=""){return '<option value="">— Pilih node —</option>'+db.assets.filter(a=>a.type!=="CUSTOMER").map(a=>'<option value="'+esc(a.id)+'" '+(a.id===value?"selected":"")+'>'+esc(a.code)+' — '+esc(a.name)+'</option>').join("")}
function openCable(c){c=c||{};$("cableId").value=c.id||"";$("cableCode").value=c.code||"";$("cableFrom").innerHTML=nodeOptions(c.from);$("cableTo").innerHTML=nodeOptions(c.to);$("cableFiberCount").value=c.fiber_count||12;$("cableLength").value=c.length_m||0;$("cableStatus").value=c.status||"ACTIVE";$("cableDialog").showModal()}
function renderConnections(){const byId=Object.fromEntries(db.assets.map(a=>[a.id,a]));const cables=Object.fromEntries((db.cables||[]).map(c=>[c.id,c]));const cores=Object.fromEntries((db.cores||[]).map(c=>[c.id,c]));$("connectionList").innerHTML=(db.coreConnections||[]).map(x=>'<div class="cable-card"><div><b>'+esc(byId[x.nodeId]?.code||x.nodeId)+'</b><span class="badge">'+esc(x.connectionType||"SPLICE")+'</span></div><div class="muted">'+esc(cables[x.inputCableId]?.code||"?")+': Core '+esc(cores[x.inputCoreId]?.core_number||"?")+' → '+esc(cables[x.outputCableId]?.code||"?")+': Core '+esc(cores[x.outputCoreId]?.core_number||"?")+'</div><div class="cable-actions"><button data-conn-edit="'+esc(x.id)+'">Edit</button><button class="danger" data-conn-del="'+esc(x.id)+'">Hapus</button></div></div>').join("")||'<p class="muted">Belum ada mapping core.</p>'}
function fillConnectionForm(x={}){const nodes=db.assets.filter(a=>a.type!=="CUSTOMER");$("connectionNode").innerHTML=nodeOptions(x.nodeId);$("connectionInputCable").innerHTML=options(db.cables||[],x.inputCableId,"— Pilih kabel —");$("connectionOutputCable").innerHTML=options(db.cables||[],x.outputCableId,"— Pilih kabel —");fillCore("connectionInputCore",x.inputCoreId,x.inputCableId);fillCore("connectionOutputCore",x.outputCoreId,x.outputCableId);$("connectionType").value=x.connectionType||"SPLICE";$("connectionStatus").value=x.status||"ACTIVE"}
function openConnection(x){x=x||{};$("connectionId").value=x.id||"";fillConnectionForm(x);$("connectionDialog").showModal()}
function renderCables(){const byId=Object.fromEntries(db.assets.map(a=>[a.id,a]));$("cableList").innerHTML='<div class="cable-grid">'+(db.cables||[]).map(c=>'<div class="cable-card"><div><b>'+esc(c.code)+'</b><span class="badge">'+esc(c.fiber_count)+' CORE</span></div><div class="route"><strong>'+esc(byId[c.from]?.code||"?")+'</strong><span>→</span><strong>'+esc(byId[c.to]?.code||"?")+'</strong></div><div class="muted">'+esc(c.length_m)+' m · '+esc(c.status)+'</div><div class="cable-actions"><button data-cable-edit="'+esc(c.id)+'">Edit</button><button class="danger" data-cable-del="'+esc(c.id)+'">Hapus</button></div></div>').join("")+'</div>'}

function renderStats(){const counts=Object.fromEntries(topology.map(t=>[t,db.assets.filter(a=>a.type===t).length]));$("stats").innerHTML=topology.map(t=>'<div class="stat"><b>'+counts[t]+'</b><span>'+t+'</span></div>').join("")+'<div class="stat"><b>'+db.cores.length+'</b><span>CORES</span></div>'}
function renderTopology(){$("topology").innerHTML=topology.map((t,i)=>'<div class="node"><b>'+t+'</b><small>'+db.assets.filter(a=>a.type===t).length+' asset</small></div>'+(i<topology.length-1?'<span class="arrow">→</span>':"")).join("")}
function renderAssets(){const q=$("search").value.toLowerCase();const a=db.assets.filter(x=>(x.code+" "+x.name+" "+x.type).toLowerCase().includes(q));$("assets").innerHTML=a.map(x=>'<div class="row"><div><b>'+esc(x.code)+'</b><div class="muted">'+esc(x.type)+' · '+esc(x.name)+'</div><div class="muted">IN: '+esc((db.cables.find(c=>c.id===x.incomingCableId)||{}).code||"—")+' · OUT: '+esc((db.cables.find(c=>c.id===x.outgoingCableId)||{}).code||"—")+'</div></div><span class="badge">'+esc(x.status)+'</span><div><button data-edit="'+esc(x.id)+'">Edit</button> <button class="danger" data-del="'+esc(x.id)+'">Hapus</button></div></div>').join("")||'<p class="muted">Tidak ada asset.</p>'}
function renderCustomers(){$("customerSelect").innerHTML=db.assets.filter(x=>x.type==="CUSTOMER").map(x=>'<option value="'+esc(x.id)+'">'+esc(x.code)+' — '+esc(x.name)+'</option>').join("")}
function renderCores(){const cables=Object.fromEntries(db.cables.map(c=>[c.id,c]));$("cores").innerHTML='<table class="table"><thead><tr><th>Cable</th><th>Core</th><th>Status</th><th>Length</th></tr></thead><tbody>'+db.cores.map(c=>'<tr><td>'+esc(cables[c.cable_id]?.code||"-")+'</td><td>'+c.core_number+'</td><td><span class="badge">'+esc(c.status)+'</span></td><td>'+esc(cables[c.cable_id]?.length_m||"-")+' m</td></tr>').join("")+'</tbody></table>'}
function openAsset(a){a=a||{};$("assetId").value=a.id||"";$("assetType").value=a.type||"OLT";$("assetCode").value=a.code||"";$("assetName").value=a.name||"";$("assetStatus").value=a.status||"ACTIVE";$("dialogTitle").textContent=a.id?"Edit Asset":"Tambah Asset";$("assetDialog").showModal()}
$("addAsset").onclick=()=>openAsset();$("addCable").onclick=()=>openCable();$("search").oninput=renderAssets;
$("assetForm").onsubmit=e=>{e.preventDefault();const id=$("assetId").value||crypto.randomUUID();const item={id,type:$("assetType").value,code:$("assetCode").value.trim(),name:$("assetName").value.trim(),status:$("assetStatus").value};if(!item.code||!item.name){alert("Kode dan nama asset wajib diisi.");return}const i=db.assets.findIndex(a=>a.id===id);if(i>=0)db.assets[i]=item;else db.assets.push(item);save();$("assetDialog").close();render()};
$("assets").onclick=e=>{const edit=e.target.dataset.edit,del=e.target.dataset.del;if(edit)openAsset(db.assets.find(a=>a.id===edit));if(del&&confirm("Hapus asset ini?")){const removed=new Set(db.cables.filter(x=>x.from===del||x.to===del).map(x=>x.id));db.assets=db.assets.filter(a=>a.id!==del);db.links=(db.links||[]).filter(x=>x.from!==del&&x.to!==del);db.cables=db.cables.filter(x=>!removed.has(x.id));db.cores=db.cores.filter(x=>!removed.has(x.cable_id));db.coreConnections=(db.coreConnections||[]).filter(x=>x.nodeId!==del&&!removed.has(x.inputCableId)&&!removed.has(x.outputCableId));save();render()}};
$("traceBtn").onclick=()=>{const c=db.assets.find(a=>a.id===$("customerSelect").value),olt=db.assets.find(a=>a.type==="OLT");if(!c){$("traceOutput").textContent="Belum ada customer.";return}const result=coreTrace(db,olt?.id,c.id);const errors=validateGraph(db).errors;if(result.found){const byId=Object.fromEntries(db.assets.map(a=>[a.id,a]));const cables=Object.fromEntries(db.cables.map(x=>[x.id,x]));const total=result.steps.filter(s=>s.kind==="CABLE").reduce((n,s)=>n+(Number(cables[s.cableId]?.length_m)||0),0);$("traceOutput").textContent=result.path.map((id,i)=>(i+1)+". "+byId[id]?.type+": "+byId[id]?.code+" — "+byId[id]?.name).join("\n")+"\n\nCORE PATH: "+result.steps.map(s=>s.kind+(s.cableId?" / "+cables[s.cableId]?.code:"")+(s.coreId?" / Core "+db.cores.find(c=>c.id===s.coreId)?.core_number:"")).join(" → ")+"\nTOTAL CABLE: "+total+" m";return}const fallback=shortestTrace(db,olt?.id,c.id);if(!fallback.found){$("traceOutput").textContent="PATH TIDAK DITEMUKAN.\n"+(errors.length?"Validasi:\n"+errors.join("\n"):"Periksa kabel dan continuity core.");return}$("traceOutput").textContent="Node path ditemukan, tetapi continuity core belum lengkap.\n\n"+fallback.path.map((x,i)=>(i+1)+". "+x.type+": "+x.code+" — "+x.name).join("\n")+"\n\nTambahkan mapping Core Continuity pada setiap JB/ODC/ODP yang dilewati."};

$("cableForm").onsubmit=e=>{e.preventDefault();const id=$("cableId").value||crypto.randomUUID(),from=$("cableFrom").value,to=$("cableTo").value,count=Math.max(1,Number($("cableFiberCount").value||1));if(!from||!to||from===to){alert("Node asal dan tujuan harus berbeda.");return}const item={id,code:$("cableCode").value.trim(),fiber_count:count,length_m:Number($("cableLength").value||0),from,to,status:$("cableStatus").value};const i=db.cables.findIndex(c=>c.id===id);if(i>=0){db.cables[i]=item;db.coreConnections=(db.coreConnections||[]).filter(x=>x.inputCableId!==id&&x.outputCableId!==id);db.cores=db.cores.filter(c=>c.cable_id!==id)}else db.cables.push(item);for(let n=1;n<=count;n++)db.cores.push({id:crypto.randomUUID(),cable_id:id,core_number:n,status:"AVAILABLE"});save();$("cableDialog").close();render()};
$("connectionInputCable").onchange=()=>fillCore("connectionInputCore","",$("connectionInputCable").value);$("connectionOutputCable").onchange=()=>fillCore("connectionOutputCore","",$("connectionOutputCable").value);
$("connectionForm").onsubmit=e=>{e.preventDefault();const id=$("connectionId").value||crypto.randomUUID(),x={id,nodeId:$("connectionNode").value,inputCableId:$("connectionInputCable").value,inputCoreId:$("connectionInputCore").value,outputCableId:$("connectionOutputCable").value,outputCoreId:$("connectionOutputCore").value,connectionType:$("connectionType").value,status:$("connectionStatus").value};if(!x.nodeId||!x.inputCableId||!x.inputCoreId||!x.outputCableId||!x.outputCoreId){alert("Node, kabel, dan core wajib diisi.");return}const validCore=(coreId,cableId)=>db.cores.some(core=>core.id===coreId&&core.cable_id===cableId);if(!validCore(x.inputCoreId,x.inputCableId)||!validCore(x.outputCoreId,x.outputCableId)){alert("Core tidak sesuai dengan kabel.");return}const i=db.coreConnections.findIndex(v=>v.id===id);if(i>=0)db.coreConnections[i]=x;else db.coreConnections.push(x);save();$("connectionDialog").close();render()};
$("connectionList").onclick=e=>{const edit=e.target.dataset.connEdit,del=e.target.dataset.connDel;if(edit)openConnection(db.coreConnections.find(x=>x.id===edit));if(del&&confirm("Hapus mapping core ini?")){db.coreConnections=db.coreConnections.filter(x=>x.id!==del);save();render()}};
$("addConnection").onclick=()=>openConnection();
$("cableList").onclick=e=>{const edit=e.target.dataset.cableEdit,del=e.target.dataset.cableDel;if(edit)openCable(db.cables.find(c=>c.id===edit));if(del&&confirm("Hapus kabel dan seluruh core kabel ini?")){db.cables=db.cables.filter(c=>c.id!==del);db.cores=db.cores.filter(c=>c.cable_id!==del);db.coreConnections=(db.coreConnections||[]).filter(x=>x.inputCableId!==del&&x.outputCableId!==del);save();render()}};
$("resetDemo").onclick=()=>{if(confirm("Reset seluruh data demo di browser?")){db=structuredClone(seed);save();render()}};
render();